name: kinfraglib
channels:
  - conda-forge
dependencies:
  # Base dependencies
  - python>=3.8
  - pip
  # Package dependencies
  - biopandas
  - chembl_webresource_client
  - ijson
  - ipywidgets>=7.5
  - jupyterlab
  - matplotlib
  - numpy
  - pandas=1.5
  - rdkit=2021.09
  - scikit-learn
  - seaborn
  - lich::syba
  - redo
  - opencadd
  ## CI tests
  - pytest=7.4
  - pytest-xdist
  - nbval
  - shyaml
  - pip:
    - swagger_spec_validator==3.0.3 # CI fails with version 3.0.4
    - black-nb
    # KinFragLib itself
    # - https://github.com/volkamerlab/kinfraglib/archive/master.tar.gz 
    - .
